### ISSUE TITLE
The screenshot is missing

### ISSUE THREAD

**Issue by haocheng** [oh-my-fish/theme-dangerous#1]
Hi, 

The screenshot seems to be missing:
https://raw.githubusercontent.com/tannhuber/media/master/dangerous.gif

Thank you!

**Comment by tannhuber** [comment]
Hi haocheng,
it's an animated gif with 29MB. If you have a slow internet connection, it probably needs some time to load. Can you check again?
Thank you!

**Comment by bobthecow** [comment]
Oh wow. It's 29mb? Is there any way we could compress that a bit?

**Comment by haocheng** [comment]
Hi, 

Not sure if it's size issue, but it shows 503 for me this morning. 
However, it seems to be working now.

Thank you!

**Comment by tannhuber** [comment]
@bobthecow I could reduce the size to 14MB without any losses. It's still large. But it's only linked into the README. So people don't need to worry about wasting space on their disks if they install the theme.

**Comment by bobthecow** [comment]
Cutting it in half would be amazing, but it might not be enough. The current file is slow even without a slow internet connection. Does raw.githubusercontent.com not do well with large files or something? Would it be worth uploading to their S3 bucket by adding it in a comment, and switch to that URL instead?

**Comment by tannhuber** [comment]
I have a slow internet connection as well. Nevertheless, my browser is able to start the animation almost instantly while it's still loading. I couldn't observe a large delay even with the 29MB file. The current version has 6MB after reducing the colour palette. The losses are acceptable. Another reduction would be possible by scaling. But it would make the font ugly and hard to read. That's why I wouldn't go below the 6MB.

**Comment by bobthecow** [comment]
Right, I wasn't suggesting reducing the quality any further. I was suggesting using something besides raw.githubusercontent to host it. This image is slow for me, even with a decently fast connection. I'm guessing that's slow because it's optimized for serving source files, not images.

**Comment by tannhuber** [comment]
Okay, the question then arises as to where the bottleneck is. If it loads fast here, I wouldn't agree that it could come from a slow raw.githubusercontent. How long does it take to load the gif on your device?
```
wget https://raw.githubusercontent.com/tannhuber/media/master/dangerous.gif
```
takes 3.9 seconds on my system which is an absolutely reasonable value for my internet connection.
