### ISSUE TITLE
How to remove a bookmark which the dir has already been deleted?

### ISSUE THREAD

**Issue by Naolador** [oh-my-fish/theme-dangerous#13]
I deleted a directory before removing it from the bookmark. Now the dir becomes unusable and I couldn't remove this one from the list by using the 'M' command. 

Where's the bookmark config file?

**Comment by acherrera** [comment]
I know this question is nearly two years old, but I ran into the same issue and thought I would share it in case anyone else came upon it.

I went through the source code and found where this was being set. If you know the name of the directory you want to remove you can use this to get ride of it:
`set -e bookmarks[(contains -i /home/usr/some_dir/ $bookmarks)]`

If you are not sure what the directory is, you can use `echo $bookmarks` to show all of the bookmarks that are being tracked.

**Comment by Naolador** [comment]
> I know this question is nearly two years old, but I ran into the same issue and thought I would share it in case anyone else came upon it.
> 
> I went through the source code and found where this was being set. If you know the name of the directory you want to remove you can use this to get ride of it: `set -e bookmarks[(contains -i /home/usr/some_dir/ $bookmarks)]`
> 
> If you are not sure what the directory is, you can use `echo $bookmarks` to show all of the bookmarks the are being tracked.

That works perfectly! Although I am already not worked for that company anymore, I could reproduce the issue on my home PC. Thank you!
