### ISSUE TITLE
Add a description to the repository

### ISSUE THREAD

**Issue by derekstavis** [oh-my-fish/theme-dangerous#4]
Oh My Fish uses Github API to fetch repository descriptions with `omf describe`. Adding a description to this project would be nice!

**Comment by tannhuber** [comment]
@bpinto I would manage this. But I've lost administrative permissions, you probably know the reason.

**Comment by bpinto** [comment]
@tannhuber yeah, I know... :disappointed: 

I have given you the admin rights, sorry for the trouble!

**Comment by tannhuber** [comment]
Thank you.
