### ISSUE TITLE
How to cleanly remove theme dangerous?

### ISSUE THREAD

**Issue by BarbzYHOOL** [oh-my-fish/theme-dangerous#9]
I wanted to test quickly but since I don't have the dependencies, it printed a lot of errors (and no time to fix them)

now I have a green [I] all the time on the left, even when i switch to another theme, how to remove this?

**Comment by BarbzYHOOL** [comment]
Hmm I think I just needed to clear this file .config/fish/fishd.94de80cc1a78

Now I can retry to install :P

**Comment by sagebind** [comment]
The green `[I]` indicates [Vi mode](https://fishshell.com/docs/current/#vi-mode), which is built in to Fish shell, which this theme encourages you enable. All you have to do is disable it again. One way to do so is to run

```
set -U fish_key_bindings fish_default_key_bindings
```

I see this confusion come up all the time; Vi mode is a _fish_ feature, not an _oh my fish_ feature.

**Comment by BarbzYHOOL** [comment]
Alright, thank you I'll remember it (I try to avoid everything related to Vim though :P)
